name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Run Build
        run: ./versions-downloader.sh

